spring: 
  datasource: 
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
    contexts: test, faker
server:
  error:
    include-stacktrace: on-param
    
   